---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[jhdc-firewall::default]
    attributes:
      fail2ban:
        services:
          sshd:
            enabled: "true"
            bantime: "3613"
          postfix:
            enabled: "true"
